###################################|###|####################################
#   _____                          |   |                                   #
#  |  __ \--.--.----.-----.-----.  |===|  This file is part of Byron       #
#  |  __ <  |  |   _|  _  |     |  |___|  evolutionary source-code fuzzer  #
#  |____/ ___  |__| |_____|__|__|   ).(   v0.8a1 "Don Juan"                #
#        |_____|                    \|/                                    #
#################################### ' #####################################

title: Byron
#description: [An evolutionary source code fuzzer]

remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme
